language: php
sudo: false
matrix:
  include:
  - php: 5.3
    dist: precise
  - php: 5.4
    dist: precise
  - php: 5.5
    dist: precise
  - php: 5.6
  - php: 7.0
  - php: 7.1
  - php: 7.2
  - php: 7.3
  fast_finish: true
script: ./test.sh
